environment: production
environmentCode:
name: ffc-pay-xb
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-xb

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-xb-config-map

containerSecret:
  name: ffc-pay-xb-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  messageQueueHost: namespace.servicebus.windows.net
  xbTopicAddress: ffc-pay-xb
  xbSubscriptionAddress: ffc-pay-xb
  xbResponseTopicAddress: ffc-pay-xb-response

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
