environment: production
environmentCode:
name: ffc-pay-xb
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-xb

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-xb-config-map

containerSecret:
  name: ffc-pay-xb-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 200Mi
  limitCpu: 100m
  messageQueueHost: namespace.servicebus.windows.net
  xbTopicAddress: ffc-pay-xb
  xbSubscriptionAddress: ffc-pay-xb
  xbResponseTopicAddress: ffc-pay-xb-response
  active: true
  mssqlHost: ffc-pay-xb-mssql
  mssqlDb: RPA.Finance.CrossBorder.PaymentEngine (Production)
  mssqlUser: not-real
  mssqlPassword: not-real

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

secretProviderClass:
  azure:
    keyvaultName: SNDFFCINFKV2001
    objects: # reading the secret from Azure Key Vault
      - objectName: appInsights-connectionString # secret name in Azure Key Vault
        objectType: secret

  secretObjects: # creating a Kubernetes secret from the Azure Key Vault secrets
    - secretName: ffc-doc-statement-data
      type: Opaque
      data:
        - objectName: appInsights-connectionString # secret name in Azure Key Vault
          key: APPLICATIONINSIGHTS_CONNECTION_STRING # the secret key in the Kubernetes secret and use in the application