services:
  ffc-pay-xb:
    build:
      context: .
      target: production
    image: ffc-pay-xb
    container_name: ffc-pay-xb
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-xb-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      XB_TOPIC_ADDRESS: ${XB_TOPIC_ADDRESS:-ffc-pay-xb}${MESSAGE_QUEUE_SUFFIX}
      XB_SUBSCRIPTION_ADDRESS: ${XB_SUBSCRIPTION_ADDRESS:-ffc-pay-xb}${MESSAGE_QUEUE_SUFFIX}
      XBRESPONSE_TOPIC_ADDRESS: ${XBRESPONSE_TOPIC_ADDRESS:-ffc-pay-xb-response}${MESSAGE_QUEUE_SUFFIX}
