services:
  ffc-pay-xb:
    build:
      context: .
      target: production
    image: ffc-pay-xb
    container_name: ffc-pay-xb
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-xb-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
