# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-xb:
    build:
      target: development
    image: ffc-pay-xb-development
    container_name: ffc-pay-xb-development
    ports:
      - "9110:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-xb-mssql:
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
